### ISSUE TITLE
[Issue] Broken version link

### ISSUE THREAD

**Issue by faelBrunnoS** [stfwi/redstonepen#4]
The check version link is broken
```java
[14:57:20] [Forge Version Check/INFO] [ne.mi.fm.VersionChecker/]: [redstonepen] Starting version check at https://raw.githubusercontent.com/stfwi/redstonepen/1.17/meta/update.json
[14:57:20] [Forge Version Check/WARN] [ne.mi.fm.VersionChecker/]: Failed to process update information
com.google.gson.JsonSyntaxException: java.lang.IllegalStateException: Expected BEGIN_OBJECT but was NUMBER at line 1 column 4 path $
	at com.google.gson.Gson.fromJson(Gson.java:944) ~[gson-2.8.8.jar%2325!/:?] {}
	at com.google.gson.Gson.fromJson(Gson.java:897) ~[gson-2.8.8.jar%2325!/:?] {}
	at com.google.gson.Gson.fromJson(Gson.java:846) ~[gson-2.8.8.jar%2325!/:?] {}
	at com.google.gson.Gson.fromJson(Gson.java:817) ~[gson-2.8.8.jar%2325!/:?] {}
	at net.minecraftforge.fml.VersionChecker$1.process(VersionChecker.java:189) ~[fmlcore-1.18.1-39.0.75.jar%23192!/:?] {}
	at java.lang.Iterable.forEach(Iterable.java:75) [?:?] {re:mixin}
	at net.minecraftforge.fml.VersionChecker$1.run(VersionChecker.java:128) [fmlcore-1.18.1-39.0.75.jar%23192!/:?] {}
Caused by: java.lang.IllegalStateException: Expected BEGIN_OBJECT but was NUMBER at line 1 column 4 path $
	at com.google.gson.stream.JsonReader.beginObject(JsonReader.java:384) ~[gson-2.8.8.jar%2325!/:?] {}
	at com.google.gson.internal.bind.MapTypeAdapterFactory$Adapter.read(MapTypeAdapterFactory.java:183) ~[gson-2.8.8.jar%2325!/:?] {}
	at com.google.gson.internal.bind.MapTypeAdapterFactory$Adapter.read(MapTypeAdapterFactory.java:145) ~[gson-2.8.8.jar%2325!/:?] {}
	at com.google.gson.Gson.fromJson(Gson.java:932) ~[gson-2.8.8.jar%2325!/:?] {}
	... 6 more

```

**Comment by stfwi** [comment]
Hi, I'm on that (restructuring the repo a bit), cheers,-

**Comment by faelBrunnoS** [comment]
Ooh okay!

**Comment by stfwi** [comment]
Oky, should be good not with the next release, I'll close. Ty again for the hint!
